name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -d -p 3000:3000 -v $(pwd):/home/node/nest_ci_api --rm --name nest_ci rodrigorrch/full_cycle_docker_exercise_5
      - run: docker exec nest_ci dockerize -timeout=180s -wait=http://localhost:3000
      - run: docker exec nest_ci npm run test